/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import type { JSX } from 'unity-ambient-x';

import { defineCustomElement as defineAdvancedSearch } from 'unity-ambient-x/dist/components/advanced-search.js';
import { defineCustomElement as defineAdvancedSearchGrouped } from 'unity-ambient-x/dist/components/advanced-search-grouped.js';
import { defineCustomElement as defineAgTable } from 'unity-ambient-x/dist/components/ag-table.js';
import { defineCustomElement as defineAmbientDemoContainer } from 'unity-ambient-x/dist/components/ambient-demo-container.js';
import { defineCustomElement as defineAmbientTemplateGrid } from 'unity-ambient-x/dist/components/ambient-template-grid.js';
import { defineCustomElement as defineAppBar } from 'unity-ambient-x/dist/components/app-bar.js';
import { defineCustomElement as defineCheckBox } from 'unity-ambient-x/dist/components/check-box.js';
import { defineCustomElement as defineChipSection } from 'unity-ambient-x/dist/components/chip-section.js';
import { defineCustomElement as defineCustomButton } from 'unity-ambient-x/dist/components/custom-button.js';
import { defineCustomElement as defineEditViewFormDialog } from 'unity-ambient-x/dist/components/edit-view-form-dialog.js';
import { defineCustomElement as defineFileUpload } from 'unity-ambient-x/dist/components/file-upload.js';
import { defineCustomElement as defineFilterConditions } from 'unity-ambient-x/dist/components/filter-conditions.js';
import { defineCustomElement as defineFluentDialog } from 'unity-ambient-x/dist/components/fluent-dialog.js';
import { defineCustomElement as defineGetUser } from 'unity-ambient-x/dist/components/get-user.js';
import { defineCustomElement as defineGridPrimaryBar } from 'unity-ambient-x/dist/components/grid-primary-bar.js';
import { defineCustomElement as defineHintPanel } from 'unity-ambient-x/dist/components/hint-panel.js';
import { defineCustomElement as defineKpiList } from 'unity-ambient-x/dist/components/kpi-list.js';
import { defineCustomElement as defineLogicalSearchIndicator } from 'unity-ambient-x/dist/components/logical-search-indicator.js';
import { defineCustomElement as defineMyComponent } from 'unity-ambient-x/dist/components/my-component.js';
import { defineCustomElement as definePageRenderer } from 'unity-ambient-x/dist/components/page-renderer.js';
import { defineCustomElement as definePrimaryActionHeader } from 'unity-ambient-x/dist/components/primary-action-header.js';
import { defineCustomElement as defineSaveViewFormDialog } from 'unity-ambient-x/dist/components/save-view-form-dialog.js';
import { defineCustomElement as defineSearchListItem } from 'unity-ambient-x/dist/components/search-list-item.js';
import { defineCustomElement as defineSelectableList } from 'unity-ambient-x/dist/components/selectable-list.js';
import { defineCustomElement as defineSideSheet } from 'unity-ambient-x/dist/components/side-sheet.js';
import { defineCustomElement as defineSideSheetContainer } from 'unity-ambient-x/dist/components/side-sheet-container.js';
import { defineCustomElement as defineSimpleCard } from 'unity-ambient-x/dist/components/simple-card.js';
import { defineCustomElement as defineStatusChip } from 'unity-ambient-x/dist/components/status-chip.js';
import { defineCustomElement as defineStencilChip } from 'unity-ambient-x/dist/components/stencil-chip.js';
import { defineCustomElement as defineStencilField } from 'unity-ambient-x/dist/components/stencil-field.js';
import { defineCustomElement as defineStencilForm } from 'unity-ambient-x/dist/components/stencil-form.js';
import { defineCustomElement as defineStencilIconButton } from 'unity-ambient-x/dist/components/stencil-icon-button.js';
import { defineCustomElement as defineStencilIconButtonGridActionHeader } from 'unity-ambient-x/dist/components/stencil-icon-button-grid-action-header.js';
import { defineCustomElement as defineStencilToggle } from 'unity-ambient-x/dist/components/stencil-toggle.js';
import { defineCustomElement as defineTestApi } from 'unity-ambient-x/dist/components/test-api.js';
import { defineCustomElement as defineTestApiUpdated } from 'unity-ambient-x/dist/components/test-api-updated.js';
import { defineCustomElement as defineTestForm } from 'unity-ambient-x/dist/components/test-form.js';
import { defineCustomElement as defineTextArea } from 'unity-ambient-x/dist/components/text-area.js';
import { defineCustomElement as defineTextField } from 'unity-ambient-x/dist/components/text-field.js';
import { defineCustomElement as defineToggleButton } from 'unity-ambient-x/dist/components/toggle-button.js';
import { defineCustomElement as defineTreeListItem } from 'unity-ambient-x/dist/components/tree-list-item.js';
import { defineCustomElement as defineUdpAdornment } from 'unity-ambient-x/dist/components/udp-adornment.js';
import { defineCustomElement as defineUdpAmbientCard } from 'unity-ambient-x/dist/components/udp-ambient-card.js';
import { defineCustomElement as defineUdpAmbientToolTip } from 'unity-ambient-x/dist/components/udp-ambient-tool-tip.js';
import { defineCustomElement as defineUdpAvatar } from 'unity-ambient-x/dist/components/udp-avatar.js';
import { defineCustomElement as defineUdpBadge } from 'unity-ambient-x/dist/components/udp-badge.js';
import { defineCustomElement as defineUdpColumnHeader } from 'unity-ambient-x/dist/components/udp-column-header.js';
import { defineCustomElement as defineUdpDateSelector } from 'unity-ambient-x/dist/components/udp-date-selector.js';
import { defineCustomElement as defineUdpDatetimeSelector } from 'unity-ambient-x/dist/components/udp-datetime-selector.js';
import { defineCustomElement as defineUdpDivider } from 'unity-ambient-x/dist/components/udp-divider.js';
import { defineCustomElement as defineUdpDynamicContainerWithMenu } from 'unity-ambient-x/dist/components/udp-dynamic-container-with-menu.js';
import { defineCustomElement as defineUdpDynamicForm } from 'unity-ambient-x/dist/components/udp-dynamic-form.js';
import { defineCustomElement as defineUdpFetch } from 'unity-ambient-x/dist/components/udp-fetch.js';
import { defineCustomElement as defineUdpFormsRenderer } from 'unity-ambient-x/dist/components/udp-forms-renderer.js';
import { defineCustomElement as defineUdpFunctionButton } from 'unity-ambient-x/dist/components/udp-function-button.js';
import { defineCustomElement as defineUdpGridLoader } from 'unity-ambient-x/dist/components/udp-grid-loader.js';
import { defineCustomElement as defineUdpHotlistForm } from 'unity-ambient-x/dist/components/udp-hotlist-form.js';
import { defineCustomElement as defineUdpLinearLoader } from 'unity-ambient-x/dist/components/udp-linear-loader.js';
import { defineCustomElement as defineUdpMenuItem } from 'unity-ambient-x/dist/components/udp-menu-item.js';
import { defineCustomElement as defineUdpNotification } from 'unity-ambient-x/dist/components/udp-notification.js';
import { defineCustomElement as defineUdpPage } from 'unity-ambient-x/dist/components/udp-page.js';
import { defineCustomElement as defineUdpPageHeader } from 'unity-ambient-x/dist/components/udp-page-header.js';
import { defineCustomElement as defineUdpPopOver } from 'unity-ambient-x/dist/components/udp-pop-over.js';
import { defineCustomElement as defineUdpPopOverGridActionHeader } from 'unity-ambient-x/dist/components/udp-pop-over-grid-action-header.js';
import { defineCustomElement as defineUdpQuestion } from 'unity-ambient-x/dist/components/udp-question.js';
import { defineCustomElement as defineUdpRadioButton } from 'unity-ambient-x/dist/components/udp-radio-button.js';
import { defineCustomElement as defineUdpSelector } from 'unity-ambient-x/dist/components/udp-selector.js';
import { defineCustomElement as defineUdpSkeletonLoading } from 'unity-ambient-x/dist/components/udp-skeleton-loading.js';
import { defineCustomElement as defineUdpSplitScreen } from 'unity-ambient-x/dist/components/udp-split-screen.js';
import { defineCustomElement as defineUdpTab } from 'unity-ambient-x/dist/components/udp-tab.js';
import { defineCustomElement as defineUdpTabs } from 'unity-ambient-x/dist/components/udp-tabs.js';
import { defineCustomElement as defineUdpTimeSelector } from 'unity-ambient-x/dist/components/udp-time-selector.js';
import { defineCustomElement as defineUdpUserCreator } from 'unity-ambient-x/dist/components/udp-user-creator.js';
import { defineCustomElement as defineUdpVerticalSpacer } from 'unity-ambient-x/dist/components/udp-vertical-spacer.js';
import { defineCustomElement as defineUnityTypography } from 'unity-ambient-x/dist/components/unity-typography.js';
import { defineCustomElement as defineUpdAlertBanner } from 'unity-ambient-x/dist/components/upd-alert-banner.js';

export const AdvancedSearch = /*@__PURE__*/createReactComponent<JSX.AdvancedSearch, HTMLAdvancedSearchElement>('advanced-search', undefined, undefined, defineAdvancedSearch);
export const AdvancedSearchGrouped = /*@__PURE__*/createReactComponent<JSX.AdvancedSearchGrouped, HTMLAdvancedSearchGroupedElement>('advanced-search-grouped', undefined, undefined, defineAdvancedSearchGrouped);
export const AgTable = /*@__PURE__*/createReactComponent<JSX.AgTable, HTMLAgTableElement>('ag-table', undefined, undefined, defineAgTable);
export const AmbientDemoContainer = /*@__PURE__*/createReactComponent<JSX.AmbientDemoContainer, HTMLAmbientDemoContainerElement>('ambient-demo-container', undefined, undefined, defineAmbientDemoContainer);
export const AmbientTemplateGrid = /*@__PURE__*/createReactComponent<JSX.AmbientTemplateGrid, HTMLAmbientTemplateGridElement>('ambient-template-grid', undefined, undefined, defineAmbientTemplateGrid);
export const AppBar = /*@__PURE__*/createReactComponent<JSX.AppBar, HTMLAppBarElement>('app-bar', undefined, undefined, defineAppBar);
export const CheckBox = /*@__PURE__*/createReactComponent<JSX.CheckBox, HTMLCheckBoxElement>('check-box', undefined, undefined, defineCheckBox);
export const ChipSection = /*@__PURE__*/createReactComponent<JSX.ChipSection, HTMLChipSectionElement>('chip-section', undefined, undefined, defineChipSection);
export const CustomButton = /*@__PURE__*/createReactComponent<JSX.CustomButton, HTMLCustomButtonElement>('custom-button', undefined, undefined, defineCustomButton);
export const EditViewFormDialog = /*@__PURE__*/createReactComponent<JSX.EditViewFormDialog, HTMLEditViewFormDialogElement>('edit-view-form-dialog', undefined, undefined, defineEditViewFormDialog);
export const FileUpload = /*@__PURE__*/createReactComponent<JSX.FileUpload, HTMLFileUploadElement>('file-upload', undefined, undefined, defineFileUpload);
export const FilterConditions = /*@__PURE__*/createReactComponent<JSX.FilterConditions, HTMLFilterConditionsElement>('filter-conditions', undefined, undefined, defineFilterConditions);
export const FluentDialog = /*@__PURE__*/createReactComponent<JSX.FluentDialog, HTMLFluentDialogElement>('fluent-dialog', undefined, undefined, defineFluentDialog);
export const GetUser = /*@__PURE__*/createReactComponent<JSX.GetUser, HTMLGetUserElement>('get-user', undefined, undefined, defineGetUser);
export const GridPrimaryBar = /*@__PURE__*/createReactComponent<JSX.GridPrimaryBar, HTMLGridPrimaryBarElement>('grid-primary-bar', undefined, undefined, defineGridPrimaryBar);
export const HintPanel = /*@__PURE__*/createReactComponent<JSX.HintPanel, HTMLHintPanelElement>('hint-panel', undefined, undefined, defineHintPanel);
export const KpiList = /*@__PURE__*/createReactComponent<JSX.KpiList, HTMLKpiListElement>('kpi-list', undefined, undefined, defineKpiList);
export const LogicalSearchIndicator = /*@__PURE__*/createReactComponent<JSX.LogicalSearchIndicator, HTMLLogicalSearchIndicatorElement>('logical-search-indicator', undefined, undefined, defineLogicalSearchIndicator);
export const MyComponent = /*@__PURE__*/createReactComponent<JSX.MyComponent, HTMLMyComponentElement>('my-component', undefined, undefined, defineMyComponent);
export const PageRenderer = /*@__PURE__*/createReactComponent<JSX.PageRenderer, HTMLPageRendererElement>('page-renderer', undefined, undefined, definePageRenderer);
export const PrimaryActionHeader = /*@__PURE__*/createReactComponent<JSX.PrimaryActionHeader, HTMLPrimaryActionHeaderElement>('primary-action-header', undefined, undefined, definePrimaryActionHeader);
export const SaveViewFormDialog = /*@__PURE__*/createReactComponent<JSX.SaveViewFormDialog, HTMLSaveViewFormDialogElement>('save-view-form-dialog', undefined, undefined, defineSaveViewFormDialog);
export const SearchListItem = /*@__PURE__*/createReactComponent<JSX.SearchListItem, HTMLSearchListItemElement>('search-list-item', undefined, undefined, defineSearchListItem);
export const SelectableList = /*@__PURE__*/createReactComponent<JSX.SelectableList, HTMLSelectableListElement>('selectable-list', undefined, undefined, defineSelectableList);
export const SideSheet = /*@__PURE__*/createReactComponent<JSX.SideSheet, HTMLSideSheetElement>('side-sheet', undefined, undefined, defineSideSheet);
export const SideSheetContainer = /*@__PURE__*/createReactComponent<JSX.SideSheetContainer, HTMLSideSheetContainerElement>('side-sheet-container', undefined, undefined, defineSideSheetContainer);
export const SimpleCard = /*@__PURE__*/createReactComponent<JSX.SimpleCard, HTMLSimpleCardElement>('simple-card', undefined, undefined, defineSimpleCard);
export const StatusChip = /*@__PURE__*/createReactComponent<JSX.StatusChip, HTMLStatusChipElement>('status-chip', undefined, undefined, defineStatusChip);
export const StencilChip = /*@__PURE__*/createReactComponent<JSX.StencilChip, HTMLStencilChipElement>('stencil-chip', undefined, undefined, defineStencilChip);
export const StencilField = /*@__PURE__*/createReactComponent<JSX.StencilField, HTMLStencilFieldElement>('stencil-field', undefined, undefined, defineStencilField);
export const StencilForm = /*@__PURE__*/createReactComponent<JSX.StencilForm, HTMLStencilFormElement>('stencil-form', undefined, undefined, defineStencilForm);
export const StencilIconButton = /*@__PURE__*/createReactComponent<JSX.StencilIconButton, HTMLStencilIconButtonElement>('stencil-icon-button', undefined, undefined, defineStencilIconButton);
export const StencilIconButtonGridActionHeader = /*@__PURE__*/createReactComponent<JSX.StencilIconButtonGridActionHeader, HTMLStencilIconButtonGridActionHeaderElement>('stencil-icon-button-grid-action-header', undefined, undefined, defineStencilIconButtonGridActionHeader);
export const StencilToggle = /*@__PURE__*/createReactComponent<JSX.StencilToggle, HTMLStencilToggleElement>('stencil-toggle', undefined, undefined, defineStencilToggle);
export const TestApi = /*@__PURE__*/createReactComponent<JSX.TestApi, HTMLTestApiElement>('test-api', undefined, undefined, defineTestApi);
export const TestApiUpdated = /*@__PURE__*/createReactComponent<JSX.TestApiUpdated, HTMLTestApiUpdatedElement>('test-api-updated', undefined, undefined, defineTestApiUpdated);
export const TestForm = /*@__PURE__*/createReactComponent<JSX.TestForm, HTMLTestFormElement>('test-form', undefined, undefined, defineTestForm);
export const TextArea = /*@__PURE__*/createReactComponent<JSX.TextArea, HTMLTextAreaElement>('text-area', undefined, undefined, defineTextArea);
export const TextField = /*@__PURE__*/createReactComponent<JSX.TextField, HTMLTextFieldElement>('text-field', undefined, undefined, defineTextField);
export const ToggleButton = /*@__PURE__*/createReactComponent<JSX.ToggleButton, HTMLToggleButtonElement>('toggle-button', undefined, undefined, defineToggleButton);
export const TreeListItem = /*@__PURE__*/createReactComponent<JSX.TreeListItem, HTMLTreeListItemElement>('tree-list-item', undefined, undefined, defineTreeListItem);
export const UdpAdornment = /*@__PURE__*/createReactComponent<JSX.UdpAdornment, HTMLUdpAdornmentElement>('udp-adornment', undefined, undefined, defineUdpAdornment);
export const UdpAmbientCard = /*@__PURE__*/createReactComponent<JSX.UdpAmbientCard, HTMLUdpAmbientCardElement>('udp-ambient-card', undefined, undefined, defineUdpAmbientCard);
export const UdpAmbientToolTip = /*@__PURE__*/createReactComponent<JSX.UdpAmbientToolTip, HTMLUdpAmbientToolTipElement>('udp-ambient-tool-tip', undefined, undefined, defineUdpAmbientToolTip);
export const UdpAvatar = /*@__PURE__*/createReactComponent<JSX.UdpAvatar, HTMLUdpAvatarElement>('udp-avatar', undefined, undefined, defineUdpAvatar);
export const UdpBadge = /*@__PURE__*/createReactComponent<JSX.UdpBadge, HTMLUdpBadgeElement>('udp-badge', undefined, undefined, defineUdpBadge);
export const UdpColumnHeader = /*@__PURE__*/createReactComponent<JSX.UdpColumnHeader, HTMLUdpColumnHeaderElement>('udp-column-header', undefined, undefined, defineUdpColumnHeader);
export const UdpDateSelector = /*@__PURE__*/createReactComponent<JSX.UdpDateSelector, HTMLUdpDateSelectorElement>('udp-date-selector', undefined, undefined, defineUdpDateSelector);
export const UdpDatetimeSelector = /*@__PURE__*/createReactComponent<JSX.UdpDatetimeSelector, HTMLUdpDatetimeSelectorElement>('udp-datetime-selector', undefined, undefined, defineUdpDatetimeSelector);
export const UdpDivider = /*@__PURE__*/createReactComponent<JSX.UdpDivider, HTMLUdpDividerElement>('udp-divider', undefined, undefined, defineUdpDivider);
export const UdpDynamicContainerWithMenu = /*@__PURE__*/createReactComponent<JSX.UdpDynamicContainerWithMenu, HTMLUdpDynamicContainerWithMenuElement>('udp-dynamic-container-with-menu', undefined, undefined, defineUdpDynamicContainerWithMenu);
export const UdpDynamicForm = /*@__PURE__*/createReactComponent<JSX.UdpDynamicForm, HTMLUdpDynamicFormElement>('udp-dynamic-form', undefined, undefined, defineUdpDynamicForm);
export const UdpFetch = /*@__PURE__*/createReactComponent<JSX.UdpFetch, HTMLUdpFetchElement>('udp-fetch', undefined, undefined, defineUdpFetch);
export const UdpFormsRenderer = /*@__PURE__*/createReactComponent<JSX.UdpFormsRenderer, HTMLUdpFormsRendererElement>('udp-forms-renderer', undefined, undefined, defineUdpFormsRenderer);
export const UdpFunctionButton = /*@__PURE__*/createReactComponent<JSX.UdpFunctionButton, HTMLUdpFunctionButtonElement>('udp-function-button', undefined, undefined, defineUdpFunctionButton);
export const UdpGridLoader = /*@__PURE__*/createReactComponent<JSX.UdpGridLoader, HTMLUdpGridLoaderElement>('udp-grid-loader', undefined, undefined, defineUdpGridLoader);
export const UdpHotlistForm = /*@__PURE__*/createReactComponent<JSX.UdpHotlistForm, HTMLUdpHotlistFormElement>('udp-hotlist-form', undefined, undefined, defineUdpHotlistForm);
export const UdpLinearLoader = /*@__PURE__*/createReactComponent<JSX.UdpLinearLoader, HTMLUdpLinearLoaderElement>('udp-linear-loader', undefined, undefined, defineUdpLinearLoader);
export const UdpMenuItem = /*@__PURE__*/createReactComponent<JSX.UdpMenuItem, HTMLUdpMenuItemElement>('udp-menu-item', undefined, undefined, defineUdpMenuItem);
export const UdpNotification = /*@__PURE__*/createReactComponent<JSX.UdpNotification, HTMLUdpNotificationElement>('udp-notification', undefined, undefined, defineUdpNotification);
export const UdpPage = /*@__PURE__*/createReactComponent<JSX.UdpPage, HTMLUdpPageElement>('udp-page', undefined, undefined, defineUdpPage);
export const UdpPageHeader = /*@__PURE__*/createReactComponent<JSX.UdpPageHeader, HTMLUdpPageHeaderElement>('udp-page-header', undefined, undefined, defineUdpPageHeader);
export const UdpPopOver = /*@__PURE__*/createReactComponent<JSX.UdpPopOver, HTMLUdpPopOverElement>('udp-pop-over', undefined, undefined, defineUdpPopOver);
export const UdpPopOverGridActionHeader = /*@__PURE__*/createReactComponent<JSX.UdpPopOverGridActionHeader, HTMLUdpPopOverGridActionHeaderElement>('udp-pop-over-grid-action-header', undefined, undefined, defineUdpPopOverGridActionHeader);
export const UdpQuestion = /*@__PURE__*/createReactComponent<JSX.UdpQuestion, HTMLUdpQuestionElement>('udp-question', undefined, undefined, defineUdpQuestion);
export const UdpRadioButton = /*@__PURE__*/createReactComponent<JSX.UdpRadioButton, HTMLUdpRadioButtonElement>('udp-radio-button', undefined, undefined, defineUdpRadioButton);
export const UdpSelector = /*@__PURE__*/createReactComponent<JSX.UdpSelector, HTMLUdpSelectorElement>('udp-selector', undefined, undefined, defineUdpSelector);
export const UdpSkeletonLoading = /*@__PURE__*/createReactComponent<JSX.UdpSkeletonLoading, HTMLUdpSkeletonLoadingElement>('udp-skeleton-loading', undefined, undefined, defineUdpSkeletonLoading);
export const UdpSplitScreen = /*@__PURE__*/createReactComponent<JSX.UdpSplitScreen, HTMLUdpSplitScreenElement>('udp-split-screen', undefined, undefined, defineUdpSplitScreen);
export const UdpTab = /*@__PURE__*/createReactComponent<JSX.UdpTab, HTMLUdpTabElement>('udp-tab', undefined, undefined, defineUdpTab);
export const UdpTabs = /*@__PURE__*/createReactComponent<JSX.UdpTabs, HTMLUdpTabsElement>('udp-tabs', undefined, undefined, defineUdpTabs);
export const UdpTimeSelector = /*@__PURE__*/createReactComponent<JSX.UdpTimeSelector, HTMLUdpTimeSelectorElement>('udp-time-selector', undefined, undefined, defineUdpTimeSelector);
export const UdpUserCreator = /*@__PURE__*/createReactComponent<JSX.UdpUserCreator, HTMLUdpUserCreatorElement>('udp-user-creator', undefined, undefined, defineUdpUserCreator);
export const UdpVerticalSpacer = /*@__PURE__*/createReactComponent<JSX.UdpVerticalSpacer, HTMLUdpVerticalSpacerElement>('udp-vertical-spacer', undefined, undefined, defineUdpVerticalSpacer);
export const UnityTypography = /*@__PURE__*/createReactComponent<JSX.UnityTypography, HTMLUnityTypographyElement>('unity-typography', undefined, undefined, defineUnityTypography);
export const UpdAlertBanner = /*@__PURE__*/createReactComponent<JSX.UpdAlertBanner, HTMLUpdAlertBannerElement>('upd-alert-banner', undefined, undefined, defineUpdAlertBanner);
